version: "3.9"

services:

  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=workgenius
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


volumes:
    postgres-data:
    redis-data:

